import time
from fonctions import *

intro = "Bonjour et bienvenue sur ce Bot d'Halloween 🎃 Le BDA te propose une nouvelle fois une aventure forte en rebondissements !\nCe soir tu vas devoir t'échapper d'un lieu hanté. Mais pour cela, tu devras surmonter de nombreux obstacles, et te libérer des maléfices qui t'ont été jetés..."
already_started = "Je vois que tu es déjà inscrit, utilises plutôt la commande /start_again si tu t'es trompé ☺️"
ask_data = "Avant de commencer on a besoin de savoir qui tu es (pour les cadeaux surtout 😉)"
recap_data = "On récapitule :"
incorrect_data = "Tu peux recommencer avec la commande /start_again s'il y a une erreur."
finish_start = "Tu peux utiliser /continuer pour continuer, /etat pour avoir un point sur ton état et /stop pour arrêter l'action en cours.\nIl ne faut pas non plus hésiter à utiliser /stop si vous avez l'impression qu'il y a un bug et que le bot ne comprend ce que vous lui dites."
success_stop = "Ok on fait une pause. "
choix = "Que souhaites tu faire ?"
invalid_input = "Je n'ai pas compris, essaie encore."
suite = "Pour découvrir la suite clique sur /continuer"
inform_stop = "Tu peux annuler à tout moment avec la commande /stop"

id_BDAmour = -430587684

empty_user = { "prénom" : "",
               "nom" : "",
               "promo" : "",
               "enregistrement" : 0,
               "fin" : 0,
               "position" : 0,
               "nbDéplacements" : 0,
               "nbTotemsDétruits" : 0,
               "poignetGauche" : False,
               "poignetDroit" : False,
               "chevilleGauche" : False,
               "chevilleDroite" : False,
               "fini" : False}

ask = [ "Quel est ton prénom ?",
        "Quel est ton nom ?",
        "Dans quelle promo es-tu ?",
        "Super merci ! J'arrête de t'embêter\nPour découvrir l'histoire utilise /continuer\nPour faire une pause à tout moment utilise /stop\nPour découvrir l'état de ton personnage utilise /etat"]
PRENOM, NOM, PROMO, FIN = range(4)

QCM, ENIGME = range(2)

promos = [ "1A", "2A", "3A"]

manoir = { 0 : { "nom" : "grenier",
                 "description" : "Tu te réveilles dans une pièce basse de plafond très poussiéreuse, on dirait un grenier. Des coffres et des malles sont entassés autour de toi, et une lucarne se détache du mur sombre. Tu remarques des traces de pas dans la poussière qui semblent se diriger vers ce qui ressemble à une trappe.",
                 "type" : "QCM",
                 "actions" : { "action1" : { "intitulé" : "Essayer d'ouvrir la trappe.",
                                             "descriptionAction" : "Malgré ta faible force physique tu parviens à ouvrir la trappe et tu découvres ce qui ressemble à un couloir en contre bas. Tu décides d'utiliser l'échelle pour descendre.\n\nCa y est tu es en bas. Mince l'échelle ! Elle vient de se replier, impossible de remonter. Tant pis continuons par là.",
                                             "résultat" : 9,
                                             "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Regarder par la lucarne.",
                                              "descriptionAction" : "Tu t'approches de la lucarne, il fait nuit. Il n'y a rien aux alentours à part des forêts à perte de vue. On dirait que tu te trouves dans grand manoir.\nTu essaies d'ouvrir la lucarne, et en forçant un peu tu y arrives ! On dirait qu'il y a un balcon juste en dessous, tu décides alors de te glisser hors du grenier et de sauter sur le balcon en contrebas.\nIl y a une porte fenêtre, elle s'ouvre ! Tu te faufiles donc à l'intérieur.",
                                              "résultat" : 1,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Examiner les malles et les coffres.",
                                              "descriptionAction" : "Tu essaies d'ouvrir tout ce qu'il y a autour de toi. Un seul coffre s'ouvre, et à l'intérieur se trouve un vieux carnet poussiéreux. ",
                                              "résultat" : 4,
                                              "exécutable" : do_nothing}}},
            1 : { "nom" : "Chambre1",
                          "description" : "Tu te trouves dans une chambre, un immense lit à baldaquins longe un des murs. Une porte fenêtre semble mener sur un balcon.\nA l'opposé se trouve une porte blanche très décorée, et à côté une autre porte entrouverte qui laisse distinguer une salle de bain.",
                          "type" : "QCM",
                          "actions" : { "action1" : { "intitulé" : "Ouvrir le placard.",
                                                      "descriptionAction" : "Alors que tu ouvres les portes du placard, tu aperçois quelque chose qui bouge derrière une pile de vêtements.",
                                                      "résultat" : 2,
                                                      "exécutable" : do_nothing},
                                        "action2" : { "intitulé" : "Aller dans la salle de bain.",
                                                      "descriptionAction" : "Tu pousses la porte et la lumière s'allume d'elle même. Tu découvres alors cette nouvelle pièce.",
                                                      "résultat" : 5,
                                                      "exécutable" : test_miroir},
                                        "action3" : { "intitulé" : "Ouvrir la porte blanche.",
                                                      "descriptionAction" : "Heureusement la porte n'est pas verrouillée, tu la pousses et te retrouves dans un vaste espace.",
                                                      "résultat" : 3,
                                                      "exécutable" : do_nothing},
                                        "action4" : { "intitulé" : "Aller sur le balcon.",
                                                      "descriptionAction" : "Il fait froid dehors. Tu ne vois rien aux alentours à part une grande forêt, tu examines alors le bâtiment : on dirait un manoir, il a l'air immense.\nTu apprends peu de chose ici, tu décides de retourner à l'intérieur.",
                                                      "résultat" : 1,
                                                      "exécutable" : do_nothing}}},
            2 : { "nom" : "Placard",
                          "description" : "Tu pousses alors les vêtements et tu découvres un farfadet qui semble avoir plus peur de toi que toi de lui. Tu essaies alors d'en apprendre un peu plus en lui promettant que tu ne lui feras aucun mal.\nIl te dit alors d'une voix chevrotante : \"Fais attention si tu croises le chemin du maître, pense à te protéger de ses canines. Lui saura garder son sang froid face à toi, mais toi...\nMaintenant laisse moi tranquille !\" Et il ferme la porte du placard d'un coup sec.",
                          "type" : "QCM",
                          "actions" : { "action1" : { "intitulé" : "Aller dans la salle de bain.",
                                                      "descriptionAction" : "Tu pousses la porte et la lumière s'allume d'elle même. Tu découvres alors cette nouvelle pièce.",
                                                      "résultat" : 5,
                                                      "exécutable" : do_nothing},
                                        "action2" : { "intitulé" : "Ouvrir la porte blanche.",
                                                      "descriptionAction" : "Heureusement la porte n'est pas verrouillée, tu la pousses et te retrouves dans un vaste espace.",
                                                      "résultat" : 3,
                                                      "exécutable" : do_nothing},
                                        "action3" : { "intitulé" : "Aller sur le balcon.",
                                                      "descriptionAction" : "Il fait froid dehors. Tu ne vois rien aux alentours à part une grande forêt. Tu examines alors le bâtiment, on dirait un manoir, il a l'air immense.\nTu apprends peu de chose ici, tu décides de retourner à l'intérieur.",
                                                      "résultat" : 1,
                                                      "exécutable" : do_nothing}}},
            3 : { "nom" : "Palier2",
                  "description" : "Tu arrives sur un palier lumineux, un grand lustre de verre est suspendu au dessus de toi. Il y a un large escalier en marbre avec de grandes marches. En te penchant par dessus la balustrade, tu estimes que tu te trouves au deuxième étage. En face de cet escalier se trouve l'entrée d'un long couloir, avec de part et d'autre deux portes joliement décorées, l'une noire et l'autre blanche.",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Prendre l'escalier, pour descendre d'un étage.",
                                              "descriptionAction" : "Tu empruntes les grandes marches de l'escalier pour découvrir un nouvel étage.",
                                              "résultat" : 20,
                                              "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Aller dans le couloir.",
                                              "descriptionAction" : "Tu pénètres dans ce long couloir qui semble ne pas avoir de fin.",
                                              "résultat" : 9,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Ouvrir la porte blanche.",
                                              "descriptionAction" : "Alors que tu ouvres la porte, la lumière du lustre projette sa lumière à l'intérieur de la pièce.",
                                              "résultat" : 1,
                                              "exécutable" : do_nothing},
                                "action4" : { "intitulé" : "Ouvrir la porte noire.",
                                              "descriptionAction" : "Alors que tu ouvres la porte, la lumière du lustre projette sa lumière à l'intérieur de la pièce.",
                                              "résultat" : 7,
                                              "exécutable" : do_nothing}}},
            4 : { "nom" : "Coffre",
                  "description" : "En le feuilletant, tu comprends que tu te trouves dans un manoir hanté et qu'il te faut t'échapper. L'auteur de ce journal s'est un jour retrouvé dans la même situation que toi et t'apprend que tu dois détruire 4 totems pour te défaire des sceaux sur tes chevilles et tes poignets.\nTu te demandes si lui a réussi à s'échapper...",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Essayer d'ouvrir la trappe.",
                                              "descriptionAction" : "Malgré ta faible force physique tu parviens à ouvrir la trappe et tu découvres ce qui ressemble à un couloir en contre bas. Tu décides d'utiliser l'échelle pour descendre.\n\nCa y est tu es en bas. Mince l'échelle ! Elle vient de se replier, impossible de remonter. Tant pis, continuons par là.",
                                              "résultat" : 9,
                                              "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Regarder par la lucarne.",
                                              "descriptionAction" : "Tu t'approches de la lucarne, il fait nuit. Il n'y a rien aux alentours à part une forêt qui s'étale à perte de vue. On dirait que tu te trouves dans grand manoir.\nTu essaies d'ouvrir la lucarne, et en forçant un peu tu y arrives ! On dirait qu'il y a un balcon juste en dessous, tu décides alors de te glisser hors du grenier et de sauter sur le balcon en contrebas.\nIl y a une porte fenêtre, elle s'ouvre ! Tu te faufiles donc à l'intérieur.",
                                              "résultat" : 1,
                                              "exécutable" : do_nothing}}},
            5 : { "nom" : "Salle de bain",
                  "description" : "La salle de bain est une pièce blanche très lumineuse avec une entrée de chaque côté : une porte blanche et une porte noire. Et entre les deux, une grande baignoire à l'italienne et un double lavabo avec un grand miroir.",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "S'admirer dans le miroir.",
                                              "descriptionAction" : "Tu remarques que le miroir est décollé du mur d'un des côtés. Tu l'examines alors d'un peu plus près et alors que tu crois avoir décrocher le miroir, celui-ci pivote et laisse apparaître un compartiment secret.",
                                              "résultat" : 6,
                                              "exécutable" : test_miroir},
                                "action2" : { "intitulé" : "Ouvrir la porte blanche.",
                                              "descriptionAction" : "Tu sors de la salle de bain par la porte blanche.",
                                              "résultat" : 1,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Ouvrir la porte noire.",
                                              "descriptionAction" : "Tu sors de la salle de bain par la porte noire.",
                                              "résultat" : 7,
                                              "exécutable" : do_nothing}}},
            6 : { "nom" : "Miroir",
                  "description" : "Dans ce renfoncement du mur, il y a un artefact étrange... De cette relique s'échappe un être d'outre-tombe ! Se dressant de toute sa hauteur, il t'adresse les mots suivants :\n\"Tu viens de découvrir le totem qui est relié au maléfice de ton poignet droit, je te félicite. Cependant, le détruire ne sera pas si aisé. Il te faudra répondre à une énigme, et gare à toi si tu te trompes... Voici l'énigme :\"",
                  "type" : "énigme",
                  "question" : "\"Quelle est la couleur favorite du maître ?\"",
                  "réponse" : "Vermeille",
                  "vrai" : { "descriptionRésultat" : "\"Bravo, c'était la bonne réponse. Je vais te délivrer de ce maléfice. Ton poignet droit est maintenant libéré, je te conseille de continuer d'explorer le manoir pour trouver les autres totems.\"\nLe démon disparait et le miroir se referme de lui même, en regardant ton poignet droit tu remarques effectivement que le sceau a disparu.",
                             "résultat" : 32,
                             "exécutable" : sceauPD},
                  "faux" : { "descriptionRésultat" : "\"Malheureusement ce n'est pas la bonne réponse. Je ne peux pas te libérer du maléfice. Reviens me voir uniquement lorsque tu auras la réponse à ma question. Mais ne crois pas t'en sortir si simplement, je ne peux pas te laisser partir comme ça.\"\nLe démon claque des doigts et tu te sens emporter par les ténèbres...",
                             "résultat" : 27,
                             "exécutable" : do_nothing}},
            7 : { "nom" : "Chambre2",
                  "description" : "En regardant autour de toi tu te rends compte que tu te trouves dans une chambre à coucher. Celle-ci est très grande et comporte un grand lit accompagné d'une table de chevet. D'un côté de la pièce, se trouve une belle porte décorée tout de noir, et de l'autre une porte plus petite qui semble donner sur une salle de bain.\nTu entends alors un bruit étouffé, en cherchant l'origine, tu remarques que le tiroir de la table de chevet se trémousse...",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Aller dans la salle de bain.",
                                              "descriptionAction" : "Tu pousses la porte et la lumière s'allume d'elle même. Tu découvres alors cette nouvelle pièce.",
                                              "résultat" : 5,
                                              "exécutable" : test_miroir},
                                "action2" : { "intitulé" : "Utiliser la porte noire.",
                                              "descriptionAction" : "Heureusement la porte n'est pas verrouillée, tu la pousses et te retrouves dans un vaste espace.",
                                              "résultat" : 3,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Aller voir la table de chevet.",
                                              "descriptionAction" : "A peine as-tu ouvert le tiroir qu'un flash lumineux t'éblouis...",
                                              "résultat" : 8,
                                              "exécutable" : do_nothing}}},
            8 : { "nom" : "Table de chevet",
                  "description" : "Alors que ta vue s'adapte à cette nouvelle luminosité, tu distingues une créature d\'un autre monde. Elle te dit alors d'une voix caverneuse :\"Que fais tu là humain ? Tu n'es pas à ta place ici. Bon si tu veux un peu d'aide réponds à ça :\"",
                  "type" : "énigme",
                  "question" : "\"Quelle type de créature est le maître ?\"\n(écris un mot uniquement ex : chien, lapin, loutre...)",
                  "réponse" : "vampire",
                  "vrai" : { "descriptionRésultat" : "\"Bravo, c'était la bonne réponse. Voici un conseil pour la suite de tes aventures : n\'oublie jamais que N=18.\"\nIl disparait et le tiroir se referme brusquement.",
                             "résultat" : 7,
                             "exécutable" : do_nothing},
                  "faux" : { "descriptionRésultat" : "\"Tsss tu n'es qu'un bon à rien comme les autres.\"\nIl disparait et le tiroir se referme brusquement.",
                             "résultat" : 7,
                             "exécutable" : do_nothing}},
            9 : { "nom" : "Couloir",
                  "description" : "Tu te trouves maintenant dans un long couloir, c'est presque difficile d'en voir les extrémités. Tu distingues cependant un canapé d'un côté, probablement un salon, et de l'autre côté un escalier, ça doit être le palier.\nAh tiens, on dirait un tableau sur le mur au milieu du couloir.",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Examiner le tableau.",
                                              "descriptionAction" : "Tu t'approches du tableau, et en y regardant de plus près tu remarques des inscriptions sur le cadre.",
                                              "résultat" : 10,
                                              "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Aller sur le palier.",
                                              "descriptionAction" : "Tu te diriges alors vers le palier à grands pas.",
                                              "résultat" : 3,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Aller dans le salon.",
                                              "descriptionAction" : "Tu prends la direction de ce salon, déterminé.",
                                              "résultat" : 13,
                                              "exécutable" : do_nothing}}},
            10 : { "nom" : "Tableau",
                  "description" : "Ce tableau dessine devant toi un nouveau monde. Treize identités se partagent cette terre. Alors que tu peines à déchiffrer les informations sur le tableau, tu t'aperçois que le tableau porte une plaque où il est inscrit : ZX°YW'WV''' 18 , CV°AY'ZC''1. Alors que tu caresses cette plaque, des chiffres ressortent aux quatre angles du tableau : 18.1, 18.9, 23.9, 23.1.",
                  "type" : "énigme",
                  "question" : "Tu sens qu'il faut appuyer sur quelque chose sur ce tableau, mais quoi ?\n(n'écris pas de phrase, juste un mot, une lettre... ce à quoi tu penses)",
                  "réponse" : "18.9",
                  "vrai" : { "descriptionRésultat" : "Alors que tu retires ton doigt du tableau, un pan entier du mur semble s'effacer, laissant apparaître une pièce sombre. En prenant ton courage à deux mains, tu te décides finalement à entrer.",
                             "résultat" : 11,
                             "exécutable" : test_penta},
                  "faux" : { "descriptionRésultat" : "Alors que tu t'attends à ce qu'il se passe quelque chose, le tableau ne bouge pas, rien ne se passe, dommage.",
                             "résultat" : 9,
                             "exécutable" : do_nothing}},
            11 : { "nom" : "Salle de sacrifice",
                  "description" : "Tes yeux s'habituent à la faible luminosité, et tu peux distinguer au sol une forme géométrique éclairée par des bougies. En y regardant de plus près, tu réalises qu'il s'agit d'un pentagramme, tracé avec... du sang ?!\nAlors que tu t'apprétais à t'enfuir, tu remarques un totem au centre. C'est probablement un totem qui te permettra de détruire un des sceaux !\nDerrière toi, le mur est toujours ouvert sur le couloir.",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Ressortir.",
                                              "descriptionAction" : "Tu laisses le pentagramme derrière toi et tu retournes dans le couloir. A peine as-tu mis un pied dehors, que le mur se referme sur le pentagramme.",
                                              "résultat" : 9,
                                              "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Entrer dans le pentagramme.",
                                              "descriptionAction" : "Tu prends ton courage à deux mains, et tu pénètres dans le pentagramme. Un démon apparait instantanément, et te toise de toute sa hauteur.",
                                              "résultat" : 12,
                                              "exécutable" : do_nothing}}},
            12 : { "nom" : "Pentagramme",
                  "description" : "Après quelques instants de silence pendant lesquels tu étais tétanisé, le démon prends enfin la parole :\n\"Comment as-tu fait pour trouver cet endroit ? ... Non ne réponds pas, tu dois être le nouveau jouet du maître. C'est le totem que tu veux n'est-ce pas ? Je peux t'aider à le détruire à condition que tu répondes correctement à ma question, sinon... Bref, allons-y, voici ma question :\"",
                  "type" : "énigme",
                  "question" : "\"Malgré ma noirceur, j'offre la promesse d'un renouveau. Quand certains se terrent, je suis un terrain de chasse pour beaucoup de créatures . Qui suis-je ?\"\n(écris l'article et le mot, ex : le lapin)",
                  "réponse" : "la nuit",
                  "vrai" : { "descriptionRésultat" : "\"Je te félicite c'est effectivement la bonne réponse, je vais détruire ce totem, ta cheville gauche sera libérée du sceau qui lui a été aposé. Mais ne t'avises pas de venir me déranger encore une fois.\"\nLe démon disparait aussi vite qu'il est apparu et laisse derrière lui le totem brisé. En y jetant un oeil, tu t'aperçois que le sceau de ta cheville a effectivement été retiré.",
                             "résultat" : 33,
                             "exécutable" : sceauCG},
                  "faux" : { "descriptionRésultat" : "\"Comme prévu, tu ne connais pas la bonne réponse, le sceau restera à sa place, et toi... Ah j'ai trouvé!\"\nA peine a t'il dit ça qu'une force t'attire, et c'est le black out.",
                             "résultat" : 25,
                             "exécutable" : do_nothing}},
            13 : { "nom" : "Salon2",
                  "description" : "Tu te trouves maintenant dans un petit salon privé avec un canapé, différents fauteuils et une table basse. Dans le fond, tu vois une une curieuse petite porte, à l'opposé de l'entrée du couloir. Sur un des murs, tu remarques un énorme trou. Ah non, il s'agit d'un vieux monte plat.",
                  "type" : "QCM",
                  "actions" : { "action1" : { "intitulé" : "Aller dans le couloir.",
                                              "descriptionAction" : "Tu te diriges donc vers le couloir.",
                                              "résultat" : 9,
                                              "exécutable" : do_nothing},
                                "action2" : { "intitulé" : "Utiliser la petite porte.",
                                              "descriptionAction" : "Tu t'approches de le petite porte et tu la pousses pour pénétrer dans cette nouvelle pièce.",
                                              "résultat" : 14,
                                              "exécutable" : do_nothing},
                                "action3" : { "intitulé" : "Examiner le monte plat.",
                                              "descriptionAction" : "En regardant le monte plat de plus près, tu te rends compte qu'il est très profond et que tu pourrais t'y faufiler. Ni une ni deux tu t'exécutes, et ce faisant tu actives le mécanisme qui fait descendre le monte plat. Tu passes d'interminables secondes à te demander si tu vas ressortir vivant de ce mur. Quand finalement tout s'arrête et la lumière apparait. Tu t'empresses donc de sortir de là sans prêter attention à ce qui t'entoure.",
                                              "résultat" : 26,
                                              "exécutable" : do_nothing}}},
            14 : { "nom" : "Cabinet de curiosités",
                           "description" : "Tu entres alors dans une pièce étroite remplie d'étagères avec toutes sortes de bibelots. La porte qui mène au salon est toujours ouverte.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Aller dans le salon.",
                                                       "descriptionAction" : "Tu franchis la porte et la referme derrière toi.",
                                                       "résultat" : 13,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Admirer les bibelots de plus près.",
                                                       "descriptionAction" : "Tu t'approches d'une des étagères pour regarder les bibelots de plus près.",
                                                       "résultat" : 15,
                                                       "exécutable" : do_nothing}}},
            15 : { "nom" : "Passage secret",
                           "description" : "Tu vois sur l'étagère toutes sortes d'artefacts, allant de papillons colorés aux pierres précieuses en passant par des fossiles.\nUn crâne attire particulièrement ton attention, on dirait qu'il est plus brillant et moins poussiéreux que le reste.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Regarder le crâne de plus près.",
                                                       "descriptionAction" : "Tu tends la main vers le crâne, et le saisis prudemment. Tu découvres alors une sorte de mécanisme en dessous et tu t'empresses de l'activer.\nL'étagère se met alors alors à trembler et s'efface pour laisser la place à un escalier sombre qui descend dans les profondeurs du manoir. Tu t'y engages alors lentement, inquiet de ce que tu pourrais y trouver.",
                                                       "résultat" : 16,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Passer son chemin et retourner dans le salon.",
                                                       "descriptionAction" : "Tu fais demi tour et quittes cette pièce en fermant la porte derrière toi.",
                                                       "résultat" : 13,
                                                       "exécutable" : do_nothing}}},
            16 : { "nom" : "Laboratoire",
                           "description" : "Tu arrives dans une pièce un peu sombre, uniquement éclairée à la bougie. En plein milieu siège une grande table avec nombre de fioles contenant des liquides aux textures et couleurs variées.\nIl y a deux entrées, une par des escaliers sombres qui montent en colimaçon, et un passage à travers la cheminée.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "S'engager dans les escaliers.",
                                                       "descriptionAction" : "Tu montes alors les escaliers et débouches dans une pièce par derrière une étagère.",
                                                       "résultat" : 14,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Prendre le passage dans la cheminée.",
                                                       "descriptionAction" : "Tu te faufiles dans le passage étroit de la cheminée et ressors dans la pièce d'à côté. Le passage se referme derrière toi.",
                                                       "résultat" : 18,
                                                       "exécutable" : do_nothing},
                                         "action3" : { "intitulé" : "Examiner les fioles.",
                                                       "descriptionAction" : "Tu t'approches de la table sur laquelle se trouve des fioles de formes et de contenus différents, mais pas d'étiquettes pour savoir ce qu'elles contiennent. Cependant, tu vois un vieux parchemin au milieu de la table et tu t'en saisis.",
                                                       "résultat" : 17,
                                                       "exécutable" : test_fioles}}},
            17 : { "nom" : "Fioles",
                           "description" : "Sur le parchemin se trouve l'inscription suivante :\n\"Des fioles de potion il te faudra choisir une des quatre\nPuisque vers l'avant il faut que tu folâtres\nLes trois autres sont remplies de poison\nMais dans une des deux fioles rouges se trouve la solution\nDeux fioles de même effet se trouvent aux extrémités\nLa seconde fiole est de couleur cyanosée\"",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Boire le contenu de la première fiole.",
                                                       "descriptionAction" : "Tu te saisis alors de la fiole et en avales le contenu. Tu ressens alors une vive douleur dans la gorge, tu portes les mains à ta gorge dans un geste vain et finis par t'évanouir à cause de la douleur...",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Boire le contenu de la deuxième fiole.",
                                                       "descriptionAction" : "Tu te saisis alors de la fiole et en avales le contenu. On dirait que rien ne se passe quand tu sens un échauffement au niveau de ton poignet droit. Là le sceau apparait brillant, on dirait qu'il est plus fort que jamais...",
                                                       "résultat" : 16,
                                                       "exécutable" : setSceauPD},
                                         "action3" : { "intitulé" : "Boire le contenu de la troisième fiole.",
                                                       "descriptionAction" : "Tu te saisis alors de la fiole et en avales le contenu. Le liquide te réchauffe alors intérieurement et tu te sens beaucoup mieux. Tu regardes alors tes mains et tu remarques que le sceau sur ton poignet gauche a disparu !",
                                                       "résultat" : 16,
                                                       "exécutable" : sceauPG},
                                         "action4" : { "intitulé" : "Boire le contenu de la quatrième fiole.",
                                                       "descriptionAction" : "Tu te saisis alors de la fiole et en avales le contenu. On dirait que rien ne se passe quand tu sens un échauffement au niveau de ta cheville gauche. Là le sceau apparait brillant, on dirait qu'il est plus fort que jamais...",
                                                       "résultat" : 17,
                                                       "exécutable" : setSceauCG}}},
            18 : { "nom" : "Salle à manger",
                           "description" : "Tu es maintenant dans une grande salle tout en longueur avec une table chargée de victuailles, on dirait que ça vient juste d'être servi. Pour entrer dans cette grande salle à manger, il y a une porte ouverte à un bout de la salle qui donne sur le palier et il y a une grande cheminée à l'autre bout.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Aller sur le palier.",
                                                       "descriptionAction" : "Tu traverses alors la pièce pour rejoindre le palier.",
                                                       "résultat" : 20,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "S'asseoir pour manger.",
                                                       "descriptionAction" : "Tu t'installes sur une chaise pour manger : après tout tu n'as rien avalé depuis que tu t'es réveillé dans ce manoir de l'enfer. Tu saisis un pilon de poulet fumant très appétissant et, alors que tu allais l'engloutir, un démon apparaît et te regarde d'un oeil noir.\n\"Comment oses tu piller la nouriture du maître ?! Son couroux va être tel que tu ne sortiras jamais d'ici ! Pour l'instant, c'est moi qui vais m'occuper de toi...\"\nIl se penche vers toi et pose la main sur ta tête. Tout se brouille autour de toi, tu es aspiré par un tourbillon de couleurs.",
                                                       "résultat" : 1,
                                                       "exécutable" : do_nothing},
                                         "action3" : { "intitulé" : "Aller voir la cheminée.",
                                                       "descriptionAction" : "Tu te rapproches alors de la cheminée sur laquelle il y a différents bibelots. Ils servent à peu près tous à faire de la lumière.",
                                                       "résultat" : 19,
                                                       "exécutable" : do_nothing}}},
            19 : { "nom" : "Cheminée",
                           "description" : "Plus particulièrement il y a une boite d'allumettes, un chandelier, une lampe à huile et une bougie.\nQui est l'intrus ?",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Attraper la boite d'allumettes.",
                                                       "descriptionAction" : "Tu l'examines sous toute les coutures mais ça ressemble à une boite d'allumettes tout à fait normale.",
                                                       "résultat" : 18,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Attraper le chandelier.",
                                                       "descriptionAction" : "Tu l'examines sous toute les coutures mais ça ressemble à un chandelier tout à fait normal.",
                                                       "résultat" : 18,
                                                       "exécutable" : do_nothing},
                                         "action3" : { "intitulé" : "Attraper la lampe à huile.",
                                                       "descriptionAction" : "Plutôt que de suivre ta main, la lampe se contente de se pencher mais reste accrochée à la cheminée. L'âtre coulisse pour laisser apparaître un passage dans lequel tu te faufiles.",
                                                       "résultat" : 16,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "Attraper la bougie.",
                                                       "descriptionAction" : "Tu l'examines sous toute les coutures mais ça ressemble à une bougie tout à fait normale.",
                                                       "résultat" : 18,
                                                       "exécutable" : do_nothing}}},
            20 : { "nom" : "Palier1",
                           "description" : "Tu es sur le palier du premier étage du manoir. Un grand escalier de marbre monte d'un côté et descend de l'autre. Tu peux aussi accéder à une grande salle à manger, et à un salon coquet.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Monter les escaliers.",
                                                       "descriptionAction" : "Tu empruntes les grandes marches de l'escalier pour découvrir un nouvel étage.",
                                                       "résultat" : 3,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Descendre les escaliers.",
                                                       "descriptionAction" : "Tu empruntes les grandes marches de l'escalier pour découvrir un nouvel étage.",
                                                       "résultat" : 24,
                                                       "exécutable" : do_nothing},
                                         "action3" : { "intitulé" : "Aller dans la salle à manger.",
                                                       "descriptionAction" : "Tu rentres donc dans cette pièce imposante.",
                                                       "résultat" : 18,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "Aller dans le salon.",
                                                       "descriptionAction" : "Tu pénètres alors dans ce salon.",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing}}},
            21 : { "nom" : "Salon1",
                           "description" : "Ce salon est un peu éclairé par la lumière de palier mais suffisament pour voir qu'il est fait pour recevoir des invités. Tu distingues une grande bibliothèque le long d'un mur, non loin se trouve un pupitre avec un gros livre poussiéreux ouvert. Près d'un des canapés se trouve une lampe, mais elle est éteinte.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Aller sur le palier.",
                                                       "descriptionAction" : "Tu retournes vers la lumière du palier.",
                                                       "résultat" : 20,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Essayer d'allumer la lumière.",
                                                       "descriptionAction" : "Tu tires sur le cordon pour allumer la lumière, mais à peine allumée, l'ampoule éclate. De la fumée sombre s'en échappe, on dirait qu'elle s'agglomère et se déplace comme mûe par une volonté propre...\nElle se dirige vers toi et plus particulièrement vers ton poignet gauche, là, le sceau apparaît plus brillant que jamais...",
                                                       "résultat" : 21,
                                                       "exécutable" : setSceauPG},
                                         "action3" : { "intitulé" : "S'approcher de la bibliothèque.",
                                                       "descriptionAction" : "Tu te diriges vers la bibliothèque pour regarder les livres.",
                                                       "résultat" : 22,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "S'intéresser au pupitre.",
                                                       "descriptionAction" : "Tu vas lire ce qu'il y a écrit sur le livre, mais en fait il n'y a qu'une petite note à la page ouverte : \n\"Si on te demande une couleur, réponds vermeille. Et ne pose pas de question s'il te plait.\"\nVoila une information pour le moins... intéressante.",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing}}},
            22 : { "nom" : "Bibliothèque",
                           "description" : "La bibliothèque est si grande qu'il y a une échelle pour attraper les livres situés en haut. Plusieurs livres attirent ton attention, il y en a des gros, des grands, des petits, des fins, des colorés, des gris...",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Attraper \"Abraham Van Houten\" de Brad Stolker.",
                                                       "descriptionAction" : "Tu te laisses emporter dans les aventure d'Abraham Van Houten : chasseur de vampires et fin chocolatier. Tu ne gagnes rien d'avoir lu ce bouquin si ce n'est l'impression d'avoir perdu ton temps.",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Attraper \"Carmilla\" de Sheridan Le Fanu.",
                                                       "descriptionAction" : "Tu te saisis alors de ce livre, mais il ne suit pas ta main, il reste accroché à la bibliothèque. Cependant, cette dernière pivote sur elle même et fait apparaître une pièce sombre dans laquelle tu entres prudemment.",
                                                       "résultat" : 23,
                                                       "exécutable" : test_Drac},
                                         "action3" : { "intitulé" : "Attraper \"Thérianthropie : de la mythologie à la pop culture\" de Jeanne Lucile.",
                                                       "descriptionAction" : "Ce livre fait l'inventaire de toutes les histoires relatives à la transformation d'hommes en animaux. Tu n'apprends rien qui pourrait d'aider à sortir, pas même comment se transformer en chauve souris.",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "Attraper \"Sorginak\" de Miguel Etxemendia.",
                                                       "descriptionAction" : "Ce bouquin te plonge dans le procès des sorcières de Zugarramurdi. Tu en apprends plus sur la politique de l'inquisition espagnole envers la sorcellerie au 17e siècle mais tu ne trouves rien qui pourrait t'aider à sortir, pas même un petit sort...",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing}}},
            23 : { "nom" : "Chambre de Dracula",
                           "description" : "Tu entres dans une pièce sombre, et tu distingues plusieurs cercueils avec de lourds couvercles. L'un d'eux semble un peu soulevé, comme si quelqu'un en était sorti...",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Retourner dans le salon.",
                                                       "descriptionAction" : "Cette pièce est vraiment trop maudite, tu préfères en sortir.",
                                                       "résultat" : 21,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Inspecter le cercueil ouvert.",
                                                       "descriptionAction" : "Tu t'approches lentement du cercueil ouvert, inquiet de ce que tu pourrais y trouver. En jetant un oeil à l'intérieur du vois un petit démon qui semble monter la garde. Surpris, il s'exclame :\n\"Et bien ! Cela fait longtemps que personne n'est parvenu jusqu'ici. Pour te féliciter et comme tu m'as l'air inoffencif, je vais détruire un totem pour toi. Tiens, ce sera celui de la cheville droite. Je te conseille de ne pas rester ici au cas où le maître reviendrait...\"",
                                                       "résultat" : 35,
                                                       "exécutable" : sceauCD}}},
            24 : { "nom" : "Entrée",
                           "description" : "Tu te trouves dans l'immense entrée du manoir, un grand escalier en marbre dessert les étages du manoir. De part et d'autre de l'escalier, il y a des portes : de l'une d'elles s'échappe un fumet délicat, l'autre est tout simple et à peine visible. En face de l'escalier se trouve de lourdes et grandes portes, serait-ce la sortie ?",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Monter les escaliers.",
                                                       "descriptionAction" : "Tu empruntes les grandes marches de l'escalier pour découvrir un nouvel étage.",
                                                       "résultat" : 20,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Tenter la porte d'entrée.",
                                                       "descriptionAction" : "Tu pousses la porte et...",
                                                       "résultat" : 31,
                                                       "exécutable" : totemsFinis},
                                         "action3" : { "intitulé" : "Utiliser la petite porte discrète.",
                                                       "descriptionAction" : "Tu pousses cette petite porte et la refermes derrière toi.",
                                                       "résultat" : 25,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "Suivre le fumet à travers la porte.",
                                                       "descriptionAction" : "Tu pousses la porte pour tenter de trouver d'où vient cette odeur.",
                                                       "résultat" : 26,
                                                       "exécutable" : do_nothing}}},
            25 : { "nom" : "Quartier des domestiques",
                           "description" : "Tu es maintenant dans le quartier des domestiques, des casiers se trouvent d'un côté de la pièce, des lits superposés de l'autre. Il n'y a qu'une porte dans cette pièce.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Utiliser la porte.",
                                                       "descriptionAction" : "Tu prends la porte pour sortir du quartier des domestiques.",
                                                       "résultat" : 24,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Examiner les casiers.",
                                                       "descriptionAction" : "Tu t'approches des casiers pour en examiner le contenu mais ne trouves rien.",
                                                       "résultat" : 25,
                                                       "exécutable" : do_nothing}}},
            26 : { "nom" : "Cuisine",
                           "description" : "Tu es arrivé dans la cuisine du manoir, et un plat sur le feu laisse échapper un doux fumet. Deux pièces sont accessibles d'un côté du mur, mais elles n'ont pas de porte. L'une ressemble à un garde manger, l'autre à une petite pièce de repos pour les employés. A l'opposé il y a une porte. Sur un des murs il y a comme un trou, ça pourrait être un monte plat.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Prendre la porte.",
                                                       "descriptionAction" : "Tu empruntes la porte et la refermes derrière toi.",
                                                       "résultat" : 24,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Aller voir dans le garde manger.",
                                                       "descriptionAction" : "Tu prends la direction du garde manger.",
                                                       "résultat" : 27,
                                                       "exécutable" : do_nothing},
                                         "action3" : { "intitulé" : "Aller dans la pièce de repos.",
                                                       "descriptionAction" : "Tu te diriges vers la pièce de repos.",
                                                       "résultat" : 28,
                                                       "exécutable" : do_nothing},
                                         "action4" : { "intitulé" : "Examiner le monte plat.",
                                                       "descriptionAction" : "Tu te faufiles à l'intérieur du monte plat et actionnes le mécanisme pour monter dans les étages du manoir.\nUne fois que le monte plat s'est arrété, tu en descends en te dépliant.",
                                                       "résultat" : 13,
                                                       "exécutable" : do_nothing}}},
            27 : { "nom" : "Garde manger",
                           "description" : "Tu es maintenant dans le garde manger, et, comme l'indique son nom, où que ton regard se pose, tu observes de la nourriture, mais il ne semble pas y avoir autre chose d'intéressant. Il n'y a qu'une seule entrée qui mène à la cuisine.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Aller dans la cuisine.",
                                                       "descriptionAction" : "Tu te diriges alors vers la cuisine.",
                                                       "résultat" : 26,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Attendre que quelque chose se passe.",
                                                       "descriptionAction" : "Tu attends, encore et encore, mais rien ne se passe. On dirait que tu as juste perdu du temps...",
                                                       "résultat" : 27,
                                                       "exécutable" : do_nothing}}},
            28 : { "nom" : "Pièce de repos",
                           "description" : "Une fois arrivé dans la salle de repos, tu ne vois pas grand chose autour de toi. Un sofa trône au milieu de la pièce avec une petite table basse.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Se poser dans le sofa.",
                                                       "descriptionAction" : "Tu t'assois, ou plutôt tu t'affales dans le sofa. Il faut dire que tu n'as pas vraiment pris de repos depuis le début de cette aventure.\nPuis, alors que tu installais les coussins autour de toi, tu trouves quelque chose sous l'un d'eux.",
                                                       "résultat" : 29,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Retourner dans la cuisine.",
                                                       "descriptionAction" : "Tu sors donc de la pièce de repos.",
                                                       "résultat" : 26,
                                                       "exécutable" : do_nothing}}},
            29 : { "nom" : "Sofa",
                           "description" : "Il s'agit d'un bout de papier sur lequel tu peux lire l'information suivante : \n\"Certains s'amusent à jouer à 3 mensonges, une vérité.\"\nHmmm...",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Se lever pour repartir.",
                                                       "descriptionAction" : "Bien que ce sofa soit confortable, il faut se lever si tu veux avoir une chance de t'échapper.",
                                                       "résultat" : 28,
                                                       "exécutable" : do_nothing},
                                         "action2" : { "intitulé" : "Chercher d'autres papiers.",
                                                       "descriptionAction" : "Tu cherches parmi les autres coussins du sofa mais tu ne trouves rien alors tu te lèves pour continuer ta lourde tâche.",
                                                       "résultat" : 28,
                                                       "exécutable" : do_nothing}}},
            30 : { "nom" : "SortieOK",
                           "description" : "Ca y est tu es dehors, plus de sceaux sataniques pour te retenir... Tu es libre ! Tu t'élances dans la nature pour mettre le plus de distance possible entre toi et le manoir.",
                           "type" : "QCM",
                           "actions" : { "action1" : { "intitulé" : "Voir la suite",
                                                       "descriptionAction" : "Bravo tu as terminé le jeu ! Merci d'avoir participé, on espère que ça t'a plu. Reste connecté, on annoncera les vainqueurs prochainement.\nA très vite à l'école pour l'afterwork des clubs de jeudi !\n(tu peux continuer à explorer le manoir si tu veux, mais ton temps lui, s'est arrété)",
                                                       "résultat" : 0,
                                                       "exécutable" : terminer  }}},
            31 : { "nom" : "SortiePasOK",
                   "description" : "Tu te retouves dehors, et alors que tu allais t'élancer dans la nature, un démon apparait devant toi et s'exclame :\n\"Où crois tu aller comme ça ?! Tu pensais qu'on t'avait oublié ? Je vais devoir te renvoyer d'où tu viens, mais mon niveau de clémence dépendra de ta réponse à cette question :\"",
                   "type" : "énigme",
                   "question" : "\"A quoi mon maître est-il allergique ?\"\n(écris un mot seulement)",
                   "réponse" : "ail",
                   "vrai" : { "descriptionRésultat" : "\"Je vois que tu es plus malin que les autres... Je vais me contenter de te renvoyer d'où tu viens.\"\nIl claque ses doigts tout devient noir.",
                              "résultat" : 0,
                              "exécutable" : do_nothing},
                   "faux" : { "descriptionRésultat" : "\"Comme je m'y attendais, tu es comme tous les autres... Je vais te renvoyer d'où tu viens en restaurant la puissance de mes sceaux.\"\nIl claque des doigts et tout devient noir.",
                              "résultat" : 0,
                              "exécutable" : setSceaux}},
            32 : { "nom" : "MiroirOK",
                   "description" : "La salle de bain est une pièce blanche très lumineuse avec une entrée de chaque côté : une porte blanche et une porte noire. Et entre les deux, une grande baignoire à l'italienne et un double lavabo avec un grand miroir.",
                   "type" : "QCM",
                   "actions" : { "action1" : { "intitulé" : "S'admirer dans le miroir.",
                                               "descriptionAction" : "Tu remarques que le miroir est décollé du mur d'un des côtés. Tu l'examines alors d'un peu plus près et alors que tu crois avoir décrocher le miroir, celui-ci pivote et laisse apparaître un compartiment secret. Dans ce renfoncement du mur, il y a un artefact étrange... Mais il est cassé, tu as déjà détruit ce totem.",
                                               "résultat" : 5,
                                               "exécutable" : test_miroir},
                                 "action2" : { "intitulé" : "Ouvrir la porte blanche.",
                                               "descriptionAction" : "Tu sors de la salle de bain par la porte blanche.",
                                               "résultat" : 1,
                                               "exécutable" : do_nothing},
                                 "action3" : { "intitulé" : "Ouvrir la porte noire.",
                                               "descriptionAction" : "Tu sors de la salle de bain par la porte noire.",
                                               "résultat" : 7,
                                               "exécutable" : do_nothing}}},
            33 : { "nom" : "Salle de sacrifice OK",
                   "description" : "Tes yeux s'habituent à la faible luminosité, et tu peux distinguer au sol une forme géométrique éclairée par des bougies. En y regardant de plus près, tu réalises qu'il s'agit d'un pentagramme, tracé avec... du sang ?!\nAlors que tu t'apprétais à t'enfuir, tu remarques un totem au centre. Mais tu es déjà passé par ici il est détruit.\nDerrière toi, le mur est toujours ouvert sur le couloir.",
                   "type" : "QCM",
                   "actions" : { "action1" : { "intitulé" : "Ressortir.",
                                               "descriptionAction" : "Tu laisses le pentagramme derrière toi et tu retournes dans le couloir. A peine as-tu mis un pied dehors, que le mur se referme sur le pentagramme.",
                                               "résultat" : 9,
                                               "exécutable" : do_nothing}}},
            34 : { "nom" : "FiolesOK",
                   "description" : "C'est le même parchemin que tout à l'heure, celui  qui t'a permis de te libérer d'un sceau.",
                   "type" : "QCM",
                   "actions" : { "action1" : { "intitulé" : "Reposer le parchemin.",
                                               "descriptionAction" : "Tu le reposes, tu n'en as plus besoin.",
                                               "résultat" : 16,
                                               "exécutable" : do_nothing}}},
            35 : { "nom" : "Chambre Dracule OK",
                   "description" : "Tu entres dans une pièce sombre, et tu distingues plusieurs cercueils avec de lourds couvercles. L'un d'eux semble un peu soulevé, c'est là que tu as vu le petit démon qui t'a aidé.",
                   "type" : "QCM",
                   "actions" : { "action1" : { "intitulé" : "Retourner dans le salon.",
                                               "descriptionAction" : "Cette pièce est vraiment trop maudite, tu préfères en sortir.",
                                               "résultat" : 21,
                                               "exécutable" : do_nothing}}}}
